name: Bump version
on:
  workflow_dispatch:
    inputs: { }
  push:
    branches:
      - main
    paths:
      - '**'
      - '!**/*.md'
      - '!.github/**'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        include:
          - prefix: pkg/cloudwatchmetrics/
          - prefix: pkg/csvexport/
          - prefix: ''

    steps:
      - uses: actions/checkout@master

      - name: '${{ matrix.prefix }} Bump version and push tag'
        uses: hennejg/github-tag-action@v4.3.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: '${{ matrix.prefix }}v'
          release_branches: 'main'
